{
 "title": "SGX Dashboard",
 "tags": [ "sgx" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "500ms, 1s, 5s, 10s, 20s, 30s, 60s, 5m, 10m, 30m, 1h, 1d"
   },
   { "name": "filter", "label": "command filter", "query": "redis" }
  ]
 },
 "panels": [
  {
   "title": "Total Enclaves Initialized",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_init_enclaves" }
   ]
  },
  {
   "title": "Active Enclaves",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_enclaves" }
   ]
  },
  {
   "title": "eBPF Total Programs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ebpf_exporter_ebpf_programs)"
    }
   ]
  },
  {
   "title": "eBPF Enabled Programs",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "ebpf_exporter_enabled_programs" }
   ]
  },
  {
   "title": "EPC Total  pages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_total_epc_pages" }
   ]
  },
  {
   "title": "EPC Free pages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_free_pages" }
   ]
  },
  {
   "title": "EPC Allocated pages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_alloc_pages" }
   ]
  },
  {
   "title": "EPC Added  pages (EADD)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_added_pages" }
   ]
  },
  {
   "title": "EPC Loaded-back pages (ELDU)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_loaded_back" }
   ]
  },
  {
   "title": "EPC Evicted  pages (EWB)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sgx_nr_reclaimed" }
   ]
  },
  {
   "title": "EPC Free pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sgx_nr_free_pages" }
   ]
  },
  {
   "title": "EPC Allocated pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sgx_nr_alloc_pages" }
   ]
  },
  {
   "title": "EPC Page Statistics [per $interval]",
   "type": "graph",
   "description": "Free EPC pages",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sgx_nr_free_pages[$interval])",
     "legendFormat": "Free"
    },
    {
     "expr": "increase(sgx_nr_evicted[$interval])",
     "legendFormat": "Evicted"
    },
    {
     "expr": "increase(sgx_nr_alloc_pages[$interval])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "increase(sgx_nr_added_pages[$interval])",
     "legendFormat": "EADD pages"
    },
    {
     "expr": "increase(sgx_nr_reclaimed[$interval])",
     "legendFormat": "EWB pages"
    },
    {
     "expr": "increase(sgx_loaded_back[$interval])",
     "legendFormat": "ELDU pages"
    }
   ]
  },
  {
   "title": "EPC Added  pages (EADD)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sgx_nr_added_pages" }
   ]
  },
  {
   "title": "EPC Loaded-back pages (ELDU)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sgx_loaded_back" }
   ]
  },
  {
   "title": "EPC Evicted  pages (EWB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sgx_nr_reclaimed" }
   ]
  },
  {
   "title": "Number of syscall_enter [per $interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ebpf_exporter_syscall_enter{command=~'$filter'}[$interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Number of syscall_exit [per $interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ebpf_exporter_syscall_exit{command=~'$filter'}[$interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Context Switched for specified PID [per $interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ebpf_exporter_context_switched_from_pid_total{command=~'$filter'}[$interval])",
     "legendFormat": "Prev_PID: {{prev_pid}}"
    },
    {
     "expr": "increase(ebpf_exporter_context_switched_to_pid_total{command=~'$filter'}[$interval])",
     "legendFormat": "Next_PID: {{next_pid}}"
    }
   ]
  },
  {
   "title": "Page Faults kernel/user [per $interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ebpf_exporter_page_fault_kernel_total[$interval])",
     "legendFormat": "Kernel: {{error_code}}"
    },
    {
     "expr": "increase(ebpf_exporter_page_fault_user_total[$interval])",
     "legendFormat": "User: {{error_code}}"
    }
   ]
  },
  {
   "title": "Cache Stats [per $interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ebpf_exporter_page_cache_ops_total[$interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "VMStat Pagefaults [per $interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pgfault[$interval])",
     "legendFormat": "Page Faults"
    },
    {
     "expr": "increase(node_vmstat_oom_kill[$interval])",
     "legendFormat": "OOM kills"
    },
    {
     "expr": "increase(node_vmstat_pgmajfault[$interval])",
     "legendFormat": "Major Page Faults"
    },
    {
     "expr": "increase(node_vmstat_pgpgin[$interval])",
     "legendFormat": "Paged-IN"
    },
    {
     "expr": "increase(node_vmstat_pgpgout[$interval])",
     "legendFormat": "Paged-OUT "
    },
    {
     "expr": "increase(node_vmstat_pswpin[$interval])",
     "legendFormat": "Swapped-IN"
    },
    {
     "expr": "increase(node_vmstat_pswpout[$interval])",
     "legendFormat": "Swapped-OUT"
    }
   ]
  }
 ]
}